[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% for commit in commits -%}
- {{ commit.message }}
{% endfor -%}

{% endif %}\
"""
trim = true
footer = ""

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_preprocessors = []
filter_commits = false
topo_order = false
sort_commits = "newest"

[[git.commit_parsers]]
message = "^Merge.*"
skip = true

[[git.commit_parsers]]
message = ".*CHANGELOG.*"
skip = true

[[git.commit_parsers]]
message = ".*[Cc]hangelog.*"
skip = true

[[git.commit_parsers]]
message = ".*chglog.*"
skip = true

[[git.commit_parsers]]
message = ".*\\[skip ci\\].*"
skip = true

[[git.commit_parsers]]
message = ".*\\[ci skip\\].*"
skip = true

[[git.commit_parsers]]
message = "^Updated CHANGELOG.*"
skip = true
